### PR TITLE
Add macOS app support via Mac Catalyst (+ bug fixes)

### PR DESCRIPTION
**Pull request by johanngan**
Turn on Mac Catalyst to add support for a macOS app. This requires one minor change for compatibility: escaping track URLs in `Tracks.db` (since URLs are real file paths on the macOS app, and can have single quotes). One noteworthy non-default config required to make the music player work without requiring additional code changes (à la `startAccessingSecurityScopedResource`) is granting read-only access to the Music Folder in the App Sandbox settings.

Minor bug fixes include not crashing at startup if no track is loaded (from a bad loop scrubber update), and properly propagating error messages with `MessageError`.

## How to transfer data between iOS/macOS apps

We should probably add some sort of data import/export feature, but until then, it's not too hard to transfer data files manually.

- The macOS data directory for a local debug build seems to be `$HOME/Library/Containers/LoopMusic.LoopMusicSwift/Data/Documents`. `Settings.plist` and `Tracks.db` can be moved freely to/from this directory.
- iOS data can be moved around the normal way through Xcode using the `Window > Devices & Simulators` window. From the settings gear icon, the container can be exported from the "Download Container" option. The data in the `Documents/` directory can be modified freely, and the new container can be imported back to the device via the "Replace Container" option.

Note that the `url` columns won't match between the macOS and iOS apps, but the app's fallback-by-track-name behavior should make the two compatible, provided the Apple Music libraries are properly synced between devices.

### CODE REVIEW

**Comment by AnonymousRandomPerson** [comment]
The data transfer directions you wrote in this PR description would be good fit for the readme.

**Comment by johanngan** [comment]
> The data transfer directions you wrote in this PR description would be good fit for the readme.

Well, I figured it's too fragile to deserve a README. It requires that you're building a dev version locally, and it assumes your devices are synced. Which is maybe okay for a command line tool, but it's silly for an app. This should really be a feature instead, and until then, the instructions are still _somewhere_.

**Comment by AnonymousRandomPerson** [comment]
At this point I'm assuming that this app is built locally, since there's no standalone executable available. I feel it's not viable for the App Store because it's impossible to add compatibility with Apple Music tracks.

**Comment by johanngan** [comment]
I agree, but I still feel that a README of this nature doesn't fit the aesthetic 🤷. It's not like it matters whether the info is in a README vs. a GitHub PR if it's not viable for the App Store anyway. If you really want, you can just copy the instructions to a README later.

**Pull request merged**
